-- 00-foundations/00-01_time_series_is_not_relational.md
-- A hypertable is a table that lies about being one table
--
-- Query 3 of 5 in this lesson, at 00-foundations/00-01_time_series_is_not_relational.md line 79.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

SELECT chunk_name, range_start, range_end
FROM timescaledb_information.chunks
WHERE hypertable_name = 'reading'
ORDER BY range_start;
