-- 02-intermediate/02-01_ctes.md
-- The CTE version
--
-- Query 1 of 2 in this lesson, at 02-intermediate/02-01_ctes.md line 57.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

WITH bounds AS (
    -- One place for the window, computed once. Stage 01 hard-coded this twice.
    SELECT
        max(ts)                                    AS data_end,
        max(ts) - interval '1 day'                 AS today_start,
        max(ts) - interval '2 days'                AS yesterday_start
    FROM reading
),
daily AS (
    -- One place for "today versus yesterday".
    SELECT
        s.id          AS signal_id,
        s.unit,
        s.normal_low,
        s.normal_high,
        avg(r.value) FILTER (
            WHERE r.ts >= b.today_start
        ) AS today_mean,
        avg(r.value) FILTER (
            WHERE r.ts <  b.today_start
              AND r.ts >= b.yesterday_start
        ) AS yesterday_mean
    FROM reading r
    JOIN signal s   ON s.id = r.signal_id
    CROSS JOIN bounds b
    WHERE r.ts >= b.yesterday_start
    GROUP BY s.id, s.unit, s.normal_low, s.normal_high
)
SELECT
    signal_id,
    unit,
    round(today_mean::numeric, 2)    AS today,
    round(yesterday_mean::numeric, 2) AS yesterday,
    round((today_mean - yesterday_mean)::numeric, 2) AS change,
    CASE
        WHEN today_mean IS NULL      THEN 'no data today'
        WHEN today_mean < normal_low  THEN 'below band'
        WHEN today_mean > normal_high THEN 'above band'
        ELSE 'in band'
    END AS verdict
FROM daily
WHERE today_mean IS NOT NULL
  AND yesterday_mean IS NOT NULL
  AND (today_mean < normal_low OR today_mean > normal_high)
ORDER BY abs(today_mean - yesterday_mean) DESC
LIMIT 10;
