-- 02-intermediate/02-01_ctes.md
-- CTEs are not just cosmetic: they change the plan
--
-- Query 2 of 2 in this lesson, at 02-intermediate/02-01_ctes.md line 152.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

EXPLAIN (ANALYZE, BUFFERS)
WITH bounds AS (SELECT max(ts) AS data_end FROM reading)
SELECT count(*) FROM reading r, bounds b WHERE r.ts >= b.data_end - interval '1 day';
