-- 04-expert/04-02_change_detection.md
-- The change detection everyone writes first
--
-- Query 1 of 5 in this lesson, at 04-expert/04-02_change_detection.md line 19.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

SELECT
    count(*) FILTER (WHERE previous IS NOT NULL)  AS comparable,
    count(*) FILTER (WHERE value = previous)      AS unchanged,
    count(*) FILTER (WHERE value <> previous)     AS changed
FROM (
    SELECT
        value,
        lag(value) OVER (PARTITION BY signal_id ORDER BY ts) AS previous
    FROM reading
    WHERE ts >= (SELECT max(ts) FROM reading) - interval '6 hours'
) t;
