-- 04-expert/04-02_change_detection.md
-- Two silences that look identical
--
-- Query 3 of 5 in this lesson, at 04-expert/04-02_change_detection.md line 106.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

SELECT
    signal_id,
    count(*) AS points,
    round(percentile_cont(0.5) WITHIN GROUP (ORDER BY gap)::numeric, 1) AS typical_gap_s,
    round(percentile_cont(0.9) WITHIN GROUP (ORDER BY gap)::numeric, 1) AS p90_gap_s,
    max(gap)::int AS worst_gap_s
FROM (
    SELECT
        signal_id,
        extract(epoch FROM ts - lag(ts)
                OVER (PARTITION BY signal_id ORDER BY ts)) AS gap
    FROM reading
    WHERE ts >= (SELECT max(ts) FROM reading) - interval '24 hours'
) t
WHERE gap IS NOT NULL
GROUP BY signal_id
ORDER BY typical_gap_s DESC
LIMIT 6;
