-- 04-expert/04-02_change_detection.md
-- What actually distinguishes them
--
-- Query 4 of 5 in this lesson, at 04-expert/04-02_change_detection.md line 160.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

WITH gaps AS (
    SELECT
        signal_id,
        extract(epoch FROM ts - lag(ts)
                OVER (PARTITION BY signal_id ORDER BY ts)) AS gap
    FROM reading
    WHERE ts >= (SELECT max(ts) FROM reading) - interval '7 days'
),
baseline AS (
    SELECT
        signal_id,
        percentile_cont(0.5) WITHIN GROUP (ORDER BY gap) AS typical_gap
    FROM gaps
    WHERE gap IS NOT NULL
    GROUP BY signal_id
)
SELECT
    g.signal_id,
    round(b.typical_gap::numeric, 1)   AS typical_s,
    max(g.gap)::int                    AS worst_s,
    round((max(g.gap) / b.typical_gap)::numeric, 0) AS times_normal
FROM gaps g
JOIN baseline b USING (signal_id)
WHERE b.typical_gap >= 60          -- only signals that are not sampled per second
GROUP BY g.signal_id, b.typical_gap
ORDER BY times_normal DESC
LIMIT 8;
