-- 04-expert/04-02_change_detection.md
-- The pitfall: a stuck sensor and a working one are the same row
--
-- Query 5 of 5 in this lesson, at 04-expert/04-02_change_detection.md line 257.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

SELECT
    s.id AS signal_id,
    s.normal_low,
    s.normal_high,
    count(r.value) AS points,
    min(r.value)  AS lowest,
    max(r.value)  AS highest
FROM signal s
LEFT JOIN reading r
       ON r.signal_id = s.id
      AND r.ts >= (SELECT max(ts) FROM reading) - interval '24 hours'
GROUP BY s.id, s.normal_low, s.normal_high
HAVING count(r.value) > 0
   AND max(r.value) = min(r.value)
   AND min(r.value) BETWEEN s.normal_low AND s.normal_high
ORDER BY s.id;
