-- 00-foundations/00-03_quality_is_data.md
-- The scale
--
-- Query 1 of 6 in this lesson, at 00-foundations/00-03_quality_is_data.md line 45.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

SELECT
    quality,
    CASE quality
        WHEN 0 THEN 'Good'
        WHEN 1 THEN 'Uncertain'
        WHEN 2 THEN 'Bad'
    END AS name,
    count(*) AS readings,
    count(value) AS with_a_value
FROM reading
GROUP BY quality
ORDER BY quality;
