-- 00-foundations/00-03_quality_is_data.md
-- Writing some
--
-- Query 2 of 6 in this lesson, at 00-foundations/00-03_quality_is_data.md line 91.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

INSERT INTO reading (ts, signal_id, value, quality, source)
VALUES
    ('2026-09-27 09:00:00+00', 'AERATION:AHU-1:DO', 2.14, 0, 'opcua'),
    ('2026-09-27 09:00:01+00', 'AERATION:AHU-1:DO', 2.09, 1, 'opcua'),
    ('2026-09-27 09:00:02+00', 'AERATION:AHU-1:DO', NULL, 2, 'opcua');
