-- 00-foundations/00-03_quality_is_data.md
-- The two aggregates, and the difference between them
--
-- Query 3 of 6 in this lesson, at 00-foundations/00-03_quality_is_data.md line 148.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

SELECT
    count(*)                AS readings_that_happened,
    count(value)            AS readings_you_can_use,
    count(*) - count(value) AS readings_with_no_value,
    avg(value)              AS mean_of_what_you_can_use
FROM reading
WHERE signal_id = 'AERATION:AHU-1:DO';
