-- 00-foundations/00-03_quality_is_data.md
-- The two aggregates, and the difference between them
--
-- Query 4 of 6 in this lesson, at 00-foundations/00-03_quality_is_data.md line 169.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

-- A question you should be suspicious of
SELECT
    signal_id,
    avg(coalesce(value, 0)) AS mean_including_fabricated_zeros
FROM reading
GROUP BY signal_id
ORDER BY mean_including_fabricated_zeros
LIMIT 5;
