-- 00-foundations/00-03_quality_is_data.md
-- The `quality = 0` is redundant for `avg`, and that redundancy is the point.
--
-- Query 6 of 6 in this lesson, at 00-foundations/00-03_quality_is_data.md line 241.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

-- Uncertain readings excluded, broken ones were already excluded by the NULL
SELECT avg(value) AS mean_of_good_and_uncertain FROM reading
WHERE signal_id = 'AERATION:AHU-1:DO' AND quality <> 2;

-- Bad readings treated as "no reading at all", which is what avg already does
SELECT avg(value) AS mean_of_everything_with_a_value FROM reading
WHERE signal_id = 'AERATION:AHU-1:DO';
