-- 02-intermediate/02-04_gaps.md
-- The complete query
--
-- Query 1 of 2 in this lesson, at 02-intermediate/02-04_gaps.md line 42.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

WITH bounds AS (
    SELECT max(ts) AS data_end FROM reading
),
-- 1. One row per signal: the most recent reading of each, and how long ago.
last_seen AS (
    SELECT
        s.id            AS signal_id,
        s.unit,
        s.deadband,
        s.sample_ms,
        max(r.ts)       AS last_reading,
        count(r.signal_id) AS total_readings
    FROM signal s
    LEFT JOIN reading r ON r.signal_id = s.id
    GROUP BY s.id, s.unit, s.deadband, s.sample_ms
),
-- 2. How much each signal moved over a recent window. A signal whose value
--    is not moving produces no rows, and that is the whole difficulty.
activity AS (
    SELECT
        signal_id,
        count(*)      AS rows_in_window,
        max(value) - min(value) AS movement
    FROM reading
    WHERE ts >= (SELECT data_end FROM bounds) - interval '2 days'
    GROUP BY signal_id
)
SELECT
    l.signal_id,
    l.unit,
    b.data_end - l.last_reading              AS silence,
    a.rows_in_window,
    round(a.movement::numeric, 3)            AS movement_in_2_days,
    l.total_readings,
    l.sample_ms,
    l.deadband,
    CASE
        WHEN l.last_reading IS NULL
            THEN 'NEVER REPORTED'
        WHEN a.rows_in_window = 0
            THEN 'silent for 2 days: steady, or dead'
        WHEN b.data_end - l.last_reading > interval '6 hours'
            THEN 'SILENT WHILE OTHERS TALK: suspect'
        WHEN a.movement < l.deadband * 3
            THEN 'moving, but barely: quiet is expected'
        ELSE 'reporting normally'
    END AS diagnosis
FROM last_seen l
CROSS JOIN bounds b
LEFT JOIN activity a ON a.signal_id = l.signal_id
ORDER BY
    CASE
        WHEN l.last_reading IS NULL THEN 0
        WHEN b.data_end - l.last_reading > interval '6 hours' THEN 1
        WHEN a.rows_in_window = 0 THEN 2
        ELSE 3
    END,
    silence DESC;
