-- 02-intermediate/02-04_gaps.md
-- The three tests, and why all three are needed
--
-- Query 2 of 2 in this lesson, at 02-intermediate/02-04_gaps.md line 157.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

-- One query: how many signals reported in the last hour, versus the hour before?
SELECT
    count(DISTINCT signal_id) FILTER (
        WHERE ts >= (SELECT max(ts) FROM reading) - interval '1 hour'
    ) AS signals_last_hour,
    count(DISTINCT signal_id) FILTER (
        WHERE ts >= (SELECT max(ts) FROM reading) - interval '2 hours'
      AND ts <  (SELECT max(ts) FROM reading) - interval '1 hour'
    ) AS signals_hour_before
FROM reading;
