-- 04-expert/04-01_time_weighted_averages.md
-- What `AVG` is actually asserting
--
-- Query 2 of 5 in this lesson, at 04-expert/04-01_time_weighted_averages.md line 46.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

SELECT
    count(*)                                    AS points,
    round(avg(extract(epoch FROM gap))::numeric, 1) AS seconds_held,
    min(extract(epoch FROM gap))::int           AS shortest,
    max(extract(epoch FROM gap))::int           AS longest
FROM (
    SELECT ts - lag(ts) OVER (ORDER BY ts) AS gap
    FROM reading
    WHERE signal_id = 'AERATION:AHU-1:DO'
      AND ts >= (SELECT max(ts) FROM reading) - interval '6 hours'
) t
WHERE gap IS NOT NULL;
