-- 04-expert/04-01_time_weighted_averages.md
-- The three numbers
--
-- Query 3 of 5 in this lesson, at 04-expert/04-01_time_weighted_averages.md line 81.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

WITH windowed AS (
    SELECT
        signal_id,
        value,
        lead(ts) OVER (PARTITION BY signal_id ORDER BY ts) - ts AS held_for
    FROM reading
    WHERE ts >= (SELECT max(ts) FROM reading) - interval '6 hours'
)
SELECT
    signal_id,
    count(value)  AS points,
    round(avg(value)::numeric, 4) AS naive,
    round((
        sum(value * extract(epoch FROM held_for)) FILTER (WHERE value IS NOT NULL)
        / sum(extract(epoch FROM held_for))
    )::numeric, 4) AS weighted,
    round((
        avg(value)
        - (sum(value * extract(epoch FROM held_for)) FILTER (WHERE value IS NOT NULL)
           / sum(extract(epoch FROM held_for)))
    )::numeric, 4) AS error
FROM windowed
WHERE signal_id IN ('UTILITY:SITE:PLANT_POWER',
                    'AERATION:AHU-1:BLOWER_RPM',
                    'AERATION:AHU-1:DO')
GROUP BY signal_id
ORDER BY points DESC;
