-- 04-expert/04-01_time_weighted_averages.md
-- The pitfall: filter after the window, and time disappears
--
-- Query 4 of 5 in this lesson, at 04-expert/04-01_time_weighted_averages.md line 174.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

WITH samples(ts, value) AS (VALUES
    (timestamptz '2026-09-28 10:00:00+00', 1.0),
    (timestamptz '2026-09-28 10:01:00+00', 2.0),
    (timestamptz '2026-09-28 10:02:00+00', NULL),   -- instrument failed
    (timestamptz '2026-09-28 10:04:00+00', 3.0),
    (timestamptz '2026-09-28 10:05:00+00', 4.0)
),
windowed AS (
    SELECT value, lead(ts) OVER (ORDER BY ts) - ts AS held_for
    FROM samples
)
SELECT
    round(avg(value)::numeric, 3) AS naive_avg,
    round((
        sum(value * extract(epoch FROM held_for))
        / sum(extract(epoch FROM held_for))
    )::numeric, 3) AS weighted_filtered_in_where,
    round((
        sum(value * extract(epoch FROM held_for))
            FILTER (WHERE value IS NOT NULL AND held_for IS NOT NULL)
        / sum(extract(epoch FROM held_for))
    )::numeric, 3) AS weighted_filtered_in_numerator
FROM windowed;
