-- 04-expert/04-01_time_weighted_averages.md
-- Report coverage, or you have not finished
--
-- Query 5 of 5 in this lesson, at 04-expert/04-01_time_weighted_averages.md line 247.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

SELECT
    round((
        sum(value * extract(epoch FROM held_for))
            FILTER (WHERE value IS NOT NULL AND held_for IS NOT NULL)
        / sum(extract(epoch FROM held_for))
    )::numeric, 3) AS average,
    round(100.0 * count(held_for) / count(*), 1) AS rows_with_a_duration
FROM (
    SELECT value, lead(ts) OVER (ORDER BY ts) - ts AS held_for
    FROM reading
    WHERE signal_id = 'AERATION:AHU-1:DO'
      AND ts >= (SELECT max(ts) FROM reading) - interval '6 hours'
) t;
