-- 03-advanced/03-04_explain.md
-- The output, top to bottom
--
-- Query 1 of 1 in this lesson, at 03-advanced/03-04_explain.md line 42.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

EXPLAIN (ANALYZE, BUFFERS)
SELECT signal_id, count(*), avg(value)
FROM reading
WHERE ts >= '2026-09-22 00:00:00+00' AND ts < '2026-09-23 00:00:00+00'
GROUP BY signal_id;
