-- 00-foundations/00-02_identity_and_values.md
-- What it costs, measured
--
-- Query 3 of 9 in this lesson, at 00-foundations/00-02_identity_and_values.md line 71.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

SELECT pg_column_size(t.*) AS bytes_per_row
FROM (SELECT ts, signal_id, value, quality, source FROM reading) t
LIMIT 1;
