-- 00-foundations/00-02_identity_and_values.md
-- The query: both protocol faces, at one instant
--
-- Query 4 of 9 in this lesson, at 00-foundations/00-02_identity_and_values.md line 94.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

BEGIN;

-- Write both protocol faces at the same instant. Run this first, or the SELECT
-- below has nothing to pivot.
INSERT INTO reading (ts, signal_id, value, quality, source) VALUES
    ('2026-09-26 12:00:00+00', 'AERATION:AHU-1:DO', 2.10, 0, 'opcua'),
    ('2026-09-26 12:00:00+00', 'AERATION:AHU-1:DO', 2.14, 0, 'modbus');

SELECT
    ts,
    max(value) FILTER (WHERE source = 'opcua')  AS opcua,
    max(value) FILTER (WHERE source = 'modbus') AS modbus,
    max(value) FILTER (WHERE source = 'modbus')
      - max(value) FILTER (WHERE source = 'opcua') AS difference
FROM reading
WHERE signal_id = 'AERATION:AHU-1:DO'
  AND ts = '2026-09-26 12:00:00+00'
GROUP BY ts
ORDER BY ts;

ROLLBACK;
