-- 00-foundations/00-02_identity_and_values.md
-- And now the reason `source` is in the primary key
--
-- Query 5 of 9 in this lesson, at 00-foundations/00-02_identity_and_values.md line 147.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

SELECT
    conname, pg_get_constraintdef(oid)
FROM pg_constraint
WHERE conrelid = 'reading'::regclass AND contype = 'p';
