-- 00-foundations/00-02_identity_and_values.md
-- The join, and why there is only one database
--
-- Query 7 of 9 in this lesson, at 00-foundations/00-02_identity_and_values.md line 179.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

SELECT
    s.id, s.unit, s.range_min, s.range_max, s.normal_low, s.normal_high,
    e.id AS equipment, e.type, s.modbus_address
FROM signal s
LEFT JOIN equipment e ON e.id = s.equipment_id
WHERE s.id LIKE 'AERATION%'
ORDER BY s.id;
