-- 00-foundations/00-02_identity_and_values.md
-- The join, and why there is only one database
--
-- Query 8 of 9 in this lesson, at 00-foundations/00-02_identity_and_values.md line 229.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

SELECT
    split_part(id, ':', 2) AS holder,
    equipment_id,
    count(*) AS signals
FROM signal
GROUP BY 1, 2
ORDER BY 1;
