-- 03-advanced/03-01_continuous_aggregates.md
-- The complete query
--
-- Query 1 of 3 in this lesson, at 03-advanced/03-01_continuous_aggregates.md line 73.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

SELECT bucket, mean, min, max, n
FROM reading_1h
WHERE signal_id = 'AERATION:AHU-1:DO'
  AND bucket >= (SELECT time_bucket('1 hour', max(ts)) FROM reading) - interval '1 day'
ORDER BY bucket;
