-- 03-advanced/03-01_continuous_aggregates.md
-- How to see the lag
--
-- Query 2 of 3 in this lesson, at 03-advanced/03-01_continuous_aggregates.md line 131.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

-- The newest bucket that actually exists, per tier.
SELECT 'reading_1m' AS tier, max(bucket) AS newest FROM reading_1m
UNION ALL
SELECT 'reading_1h', max(bucket) FROM reading_1h
UNION ALL
SELECT 'reading', max(ts) FROM reading;
