-- 03-advanced/03-01_continuous_aggregates.md
-- Gaps survive the rollup — differently
--
-- Query 3 of 3 in this lesson, at 03-advanced/03-01_continuous_aggregates.md line 184.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

-- Signals that have gone quiet, measured at the hourly tier.
-- The bug: this cannot return a signal with no buckets at all, for exactly the
-- reason 02-04 opens with. A `GROUP BY` over readings never mentions the
-- signals that are missing from the readings.
SELECT s.id, s.unit, max(h.bucket) AS last_hour
FROM signal s
LEFT JOIN reading_1h h ON h.signal_id = s.id
GROUP BY s.id, s.unit
HAVING max(h.bucket) IS NULL
    OR max(h.bucket) < (SELECT max(bucket) FROM reading_1h) - interval '2 hours'
ORDER BY last_hour NULLS FIRST;
