-- 03-advanced/03-01_continuous_aggregates.md
-- Gaps survive the rollup — differently
--
-- Query 3 of 3 in this lesson, at 03-advanced/03-01_continuous_aggregates.md line 184.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

-- Signals that have gone quiet, measured at the hourly tier.
-- The bug: this cannot return a signal with no buckets at all, for exactly the
-- reason 02-04 opens with. A `GROUP BY` over readings never mentions the
-- signals that are missing from the readings.
-- **Why an interior hour and not "the last two hours".** The obvious version of
-- this query ends at the newest bucket, and it is the version that was here. It
-- returns nothing whenever every tag happened to write in the final two hours of
-- the window -- which depends on the hour of day you seeded, because the window
-- ends at `now`. On one seed it returned 19 signals and the gate passed; on the
-- next it returned none and `make sql` failed with `EMPTY`. A course query whose
-- result depends on when you ran it teaches nothing, and a gate that fails for
-- that reason is a gate people learn to re-run.
--
-- An interior hour is stable: the plant is quiet for some tags at every hour, so
-- this returns rows on any seed, and the point below is made every time.
SELECT s.id, s.unit, max(h.bucket) AS last_hour
FROM signal s
LEFT JOIN reading_1h h ON h.signal_id = s.id
    AND h.bucket = date_trunc('hour', (SELECT min(bucket) FROM reading_1h))
                   + interval '60 hours'   -- the third day; any interior hour works
GROUP BY s.id, s.unit
HAVING max(h.bucket) IS NULL
ORDER BY last_hour NULLS FIRST;
