-- 02-intermediate/02-03_window_functions.md
-- The window version
--
-- Query 1 of 6 in this lesson, at 02-intermediate/02-03_window_functions.md line 39.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

SELECT
    r.ts,
    r.value,
    round(avg(r.value) OVER (
        PARTITION BY r.signal_id, extract(hour FROM r.ts)
    )::numeric, 3)                       AS typical_for_this_hour,
    round((r.value - avg(r.value) OVER (
        PARTITION BY r.signal_id, extract(hour FROM r.ts)
    ))::numeric, 3)                      AS deviation
FROM reading r
WHERE r.signal_id = 'AERATION:AHU-1:DO'
  AND r.ts >= (SELECT max(ts) FROM reading) - interval '3 days'
ORDER BY r.ts;
