-- 02-intermediate/02-03_window_functions.md
-- `ORDER BY` changes the answer, and that is the trap
--
-- Query 2 of 6 in this lesson, at 02-intermediate/02-03_window_functions.md line 94.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

-- Without ORDER BY: the frame is the whole partition
SELECT ts, sum(value) OVER (PARTITION BY signal_id)
FROM reading WHERE signal_id = 'AERATION:AHU-1:DO';

-- With ORDER BY: the frame is rows up to and including the current one
SELECT ts, sum(value) OVER (PARTITION BY signal_id ORDER BY ts)
FROM reading WHERE signal_id = 'AERATION:AHU-1:DO';
