-- 02-intermediate/02-03_window_functions.md
-- `lag` and `lead` — the previous and next value
--
-- Query 3 of 5 in this lesson, at 02-intermediate/02-03_window_functions.md line 132.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

WITH hourly AS (
    SELECT
        time_bucket(interval '1 hour', ts) AS bucket,
        avg(value)                         AS mean_do
    FROM reading
    WHERE signal_id = 'AERATION:AHU-1:DO'
      AND ts >= (SELECT max(ts) FROM reading) - interval '2 days'
    GROUP BY 1
)
SELECT
    bucket,
    round(mean_do::numeric, 3)                AS mean_do,
    round(lag(mean_do)  OVER w::numeric, 3)   AS previous,
    round(lead(mean_do) OVER w::numeric, 3)   AS next,
    round((mean_do - lag(mean_do) OVER w)::numeric, 3) AS change
FROM hourly
WINDOW w AS (ORDER BY bucket)
ORDER BY bucket;
