-- 02-intermediate/02-03_window_functions.md
-- `rank` — position within a group
--
-- Query 4 of 6 in this lesson, at 02-intermediate/02-03_window_functions.md line 186.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

SELECT
    s.id AS signal_id,
    s.unit,
    date_trunc('day', r.ts) AS day,
    round(avg(r.value)::numeric, 3) AS mean_value,
    rank() OVER (
        PARTITION BY date_trunc('day', r.ts)
        ORDER BY avg(r.value) DESC
    )                       AS rank_that_day
FROM reading r
JOIN signal s ON s.id = r.signal_id
WHERE r.signal_id IN ('EFFLUENT:FLOW:NH4', 'AERATION:AHU-1:NH4_OUT')
  AND r.ts >= (SELECT max(ts) FROM reading) - interval '2 days'
GROUP BY s.id, s.unit, date_trunc('day', r.ts)
ORDER BY day, rank_that_day;
