-- 02-intermediate/02-03_window_functions.md
-- `ntile` — split into buckets
--
-- Query 5 of 6 in this lesson, at 02-intermediate/02-03_window_functions.md line 247.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

SELECT
    signal_id,
    ntile(4) OVER (ORDER BY avg(value)) AS quartile
FROM reading
WHERE ts >= (SELECT max(ts) FROM reading) - interval '1 day'
GROUP BY signal_id;
