-- 02-intermediate/02-03_window_functions.md
-- The classic mistake: a window function in `WHERE`
--
-- Query 6 of 6 in this lesson, at 02-intermediate/02-03_window_functions.md line 276.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

WITH scored AS (
    SELECT
        r.signal_id,
        avg(r.value) OVER (PARTITION BY r.signal_id) AS signal_mean
    FROM reading r
    WHERE r.ts >= (SELECT max(ts) FROM reading) - interval '1 day'
)
SELECT DISTINCT ON (sc.signal_id)
    sc.signal_id,
    round(sc.signal_mean::numeric, 3) AS signal_mean,
    s.unit,
    s.normal_high
FROM scored sc
JOIN signal s ON s.id = sc.signal_id
WHERE sc.signal_mean > s.normal_high
ORDER BY sc.signal_id, sc.signal_mean DESC;
