-- 04-expert/04-03_fixing_a_slow_query.md
-- Two versions of one query
--
-- Query 1 of 2 in this lesson, at 04-expert/04-03_fixing_a_slow_query.md line 19.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

EXPLAIN (ANALYZE, BUFFERS, TIMING OFF)
SELECT avg(value) FROM reading WHERE signal_id = 'AERATION:AHU-1:DO';
