-- 03-advanced/03-02_chunks.md
-- What chunk exclusion actually does
--
-- Query 1 of 2 in this lesson, at 03-advanced/03-02_chunks.md line 41.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

-- One hour of one day. Which chunks can possibly hold it?
SELECT count(*) AS chunks_touched
FROM timescaledb_information.chunks
WHERE hypertable_name = 'reading'
  AND range_start <= '2026-09-22 14:00:00+00'
  AND range_end   >  '2026-09-22 13:00:00+00';
