-- 03-advanced/03-03_retention.md
-- What will be deleted, and when
--
-- Query 1 of 1 in this lesson, at 03-advanced/03-03_retention.md line 63.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

WITH bounds AS (
    SELECT max(ts) AS newest FROM reading
),
policies AS (
    SELECT
        'reading'::text  AS relation, 7::int AS keep_days,
        interval '1 day' AS chunk_width
    UNION ALL
    SELECT 'reading_1m', 90, interval '1 day'
)
SELECT
    p.relation,
    p.keep_days,
    b.newest - make_interval(days => p.keep_days) AS cutoff,
    date_trunc('day', b.newest - make_interval(days => p.keep_days))
        - p.chunk_width                       AS whole_chunks_go,
    date_trunc('day', min(r.ts))               AS oldest_surviving,
    b.newest - date_trunc('day', min(r.ts))    AS actual_age
FROM policies p
CROSS JOIN bounds b
JOIN reading r ON true
GROUP BY p.relation, p.keep_days, b.newest, p.chunk_width;
