-- 04-expert/04-04_the_dashboard_query.md
-- Decision 2: what is a five-second bucket supposed to mean?
--
-- Query 1 of 4 in this lesson, at 04-expert/04-04_the_dashboard_query.md line 50.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

WITH windowed AS (
    SELECT
        time_bucket(INTERVAL '5 seconds', ts) AS bucket,
        value,
        ts,
        lead(ts) OVER (
            PARTITION BY time_bucket(INTERVAL '5 seconds', ts) ORDER BY ts
        ) - ts AS held_for
    FROM reading
    WHERE signal_id = 'PRIMARY:PRI-SCR-1:TORQUE'
      AND ts >= (SELECT max(ts) FROM reading) - interval '1 hour'
      AND value IS NOT NULL
),
per_bucket AS (
    SELECT
        bucket,
        avg(value) AS naive_avg,
        (sum(value * extract(epoch FROM held_for))
             FILTER (WHERE held_for IS NOT NULL)
         / NULLIF(sum(extract(epoch FROM held_for)), 0)) AS time_weighted,
        (array_agg(value ORDER BY ts DESC))[1] AS last_value
    FROM windowed
    GROUP BY bucket
)
SELECT
    count(*)                                            AS buckets,
    round(avg(abs(naive_avg - last_value))::numeric, 3)     AS avg_dev_from_last,
    round(max(abs(naive_avg - last_value))::numeric, 3)     AS worst_dev_from_last,
    round(avg(abs(time_weighted - last_value))::numeric, 3) AS weighted_dev_from_last
FROM per_bucket;
