-- 04-expert/04-04_the_dashboard_query.md
-- Decision 1: `AVG` is not a slightly-wrong time-weighted mean
--
-- Query 1 of 3 in this lesson, at 04-expert/04-04_the_dashboard_query.md line 56.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

WITH windowed AS (
    SELECT
        time_bucket(INTERVAL '5 seconds', ts) AS bucket,
        value,
        ts,
        lead(ts) OVER (
            PARTITION BY time_bucket(INTERVAL '5 seconds', ts) ORDER BY ts
        ) - ts AS held_for
    FROM reading
    WHERE signal_id = 'PRIMARY:PRI-SCR-1:TORQUE'
      AND ts >= (SELECT max(ts) FROM reading) - interval '1 hour'
),
bucketed AS (
    SELECT
        bucket,
        count(*) AS samples,
        avg(value) AS naive_avg,
        (array_agg(value ORDER BY ts DESC))[1] AS last_value,
        (sum(value * extract(epoch FROM held_for))
             FILTER (WHERE held_for IS NOT NULL)
         / NULLIF(sum(extract(epoch FROM held_for)), 0)) AS time_weighted
    FROM windowed
    GROUP BY bucket
)
SELECT
    bucket,
    samples,
    round(naive_avg::numeric, 3)                  AS old_avg,
    round(last_value::numeric, 3)                 AS new_last,
    round(time_weighted::numeric, 3)              AS weighted,
    round(abs(naive_avg - last_value)::numeric, 3) AS old_was_off_by
FROM bucketed
WHERE naive_avg IS NOT NULL AND last_value IS NOT NULL
ORDER BY old_was_off_by DESC
LIMIT 5;
