-- 04-expert/04-04_the_dashboard_query.md
-- How wrong was it, and on which signals
--
-- Query 2 of 3 in this lesson, at 04-expert/04-04_the_dashboard_query.md line 137.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

WITH windowed AS (
    SELECT
        signal_id,
        time_bucket(INTERVAL '5 seconds', ts) AS bucket,
        value,
        ts
    FROM reading
    WHERE ts >= (SELECT max(ts) FROM reading) - interval '1 hour'
      AND signal_id IN ('PRIMARY:PRI-SCR-1:TORQUE',
                        'UTILITY:SITE:PLANT_POWER',
                        'AERATION:AHU-1:BLOWER_VALVE',
                        'AERATION:AHU-1:DO',
                        'INFLUENT:FLOW:TURBIDITY',
                        'INFLUENT:FLOW:PH')
)
SELECT
    signal_id,
    count(*)                                              AS buckets,
    round(avg(abs(naive_avg - last_value))::numeric, 3)  AS mean_off_by,
    round(max(abs(naive_avg - last_value))::numeric, 3)  AS worst_off_by
FROM (
    SELECT
        signal_id,
        bucket,
        avg(value) AS naive_avg,
        (array_agg(value ORDER BY ts DESC))[1] AS last_value
    FROM windowed
    GROUP BY signal_id, bucket
    HAVING count(value) > 0
) AS bucketed
WHERE naive_avg IS NOT NULL AND last_value IS NOT NULL
GROUP BY signal_id
ORDER BY worst_off_by DESC
LIMIT 6;
