-- 04-expert/04-04_the_dashboard_query.md
-- The finished query
--
-- Query 4 of 4 in this lesson, at 04-expert/04-04_the_dashboard_query.md line 191.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

SELECT
    time_bucket(INTERVAL '5 seconds', ts)  AS time,
    (array_agg(value ORDER BY ts DESC))[1] AS value,     -- 04-04: last, not avg
    max(quality)                           AS quality,   -- 04-01: the caveat travels
    count(*)                               AS samples    -- 04-02: how much was there
FROM reading
WHERE signal_id = 'PRIMARY:PRI-SCR-1:TORQUE'
  AND ts >= (SELECT max(ts) FROM reading) - interval '1 hour'  -- 04-03: chunk exclusion
  AND ts <= (SELECT max(ts) FROM reading)
GROUP BY time
ORDER BY time
LIMIT 5;
