-- 02-intermediate/02-02_joins.md
-- `LEFT JOIN`, which is the one you want
--
-- Query 1 of 3 in this lesson, at 02-intermediate/02-02_joins.md line 41.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

SELECT
    s.id AS signal_id,
    s.unit,
    count(r.signal_id) AS readings_today,
    max(r.ts)         AS last_seen
FROM signal s
LEFT JOIN reading r
       ON r.signal_id = s.id
      AND r.ts >= (SELECT max(ts) FROM reading) - interval '1 day'
      AND r.ts <  (SELECT max(ts) FROM reading)
GROUP BY s.id, s.unit
HAVING count(r.signal_id) = 0
ORDER BY s.id;
