-- 02-intermediate/02-02_joins.md
-- The three kinds of "no data", and telling them apart
--
-- Query 2 of 3 in this lesson, at 02-intermediate/02-02_joins.md line 102.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

WITH today AS (
    SELECT max(ts) AS data_end FROM reading
),
status AS (
    SELECT
        s.id                                   AS signal_id,
        s.unit,
        s.sample_ms,
        count(r.signal_id) AS readings_today
    FROM signal s
    CROSS JOIN today t
    LEFT JOIN reading r
           ON r.signal_id = s.id
          AND r.ts >= t.data_end - interval '1 day'
          AND r.ts <  t.data_end
    GROUP BY s.id, s.unit, s.sample_ms
)
SELECT
    signal_id,
    unit,
    sample_ms,
    readings_today,
    CASE
        WHEN sample_ms >= 3600000 AND readings_today <= 24 THEN
            'sampled hourly or slower: few rows is expected'
        WHEN readings_today = 0 THEN
            'NO DATA: either the plant was steady, or the instrument is gone'
        WHEN readings_today < 10 THEN
            'suspiciously few readings'
        ELSE 'reporting normally'
    END AS diagnosis
FROM status
WHERE readings_today < 10
ORDER BY readings_today, signal_id;
