-- 02-intermediate/02-02_joins.md
-- (no heading above this query)
--
-- Query 3 of 3 in this lesson, at 02-intermediate/02-02_joins.md line 196.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

-- How long since this signal last produced anything at all?
SELECT
    s.id AS signal_id,
    s.unit,
    s.sample_ms,
    (SELECT max(ts) FROM reading) - max(r.ts) AS silence
FROM signal s
LEFT JOIN reading r ON r.signal_id = s.id
GROUP BY s.id, s.unit, s.sample_ms
HAVING max(r.ts) IS NOT NULL
ORDER BY silence DESC
LIMIT 8;
