-- 01-beginner/01-01_ask_a_question.md
-- The specific version
--
-- Query 2 of 6 in this lesson, at 01-beginner/01-01_ask_a_question.md line 21.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

SELECT ts, value, quality, source
FROM reading
WHERE signal_id = 'AERATION:AHU-1:DO'
ORDER BY ts DESC
LIMIT 10;
