-- 01-beginner/01-01_ask_a_question.md
-- Why the timestamps are far apart, and what that means
--
-- Query 3 of 6 in this lesson, at 01-beginner/01-01_ask_a_question.md line 82.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

-- How much did each signal actually move over the last day?
SELECT
    signal_id,
    count(*)                    AS readings,
    max(value) - min(value)     AS range_moved
FROM reading
WHERE ts >= (SELECT max(ts) FROM reading) - interval '1 day'
GROUP BY signal_id
ORDER BY readings DESC
LIMIT 8;
