-- 01-beginner/01-01_ask_a_question.md
-- The one query worth memorising
--
-- Query 4 of 6 in this lesson, at 01-beginner/01-01_ask_a_question.md line 101.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

SELECT
    r.ts,
    r.value,
    r.quality,
    s.unit,
    s.range_min,
    s.range_max,
    s.normal_low,
    s.normal_high
FROM reading r
JOIN signal s ON s.id = r.signal_id
WHERE r.signal_id = 'AERATION:AHU-1:DO'
ORDER BY r.ts DESC
LIMIT 5;
