-- 01-beginner/01-01_ask_a_question.md
-- When there is no data at all
--
-- Query 6 of 6 in this lesson, at 01-beginner/01-01_ask_a_question.md line 159.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

SELECT r.signal_id, count(*) AS n, s.deadband, s.unit
FROM reading r JOIN signal s ON s.id = r.signal_id
WHERE r.ts >= (SELECT max(ts) FROM reading) - interval '1 day'
GROUP BY 1, 3, 4
ORDER BY n DESC
LIMIT 5;
