-- 01-beginner/01-04_time_buckets.md
-- The obvious attempt
--
-- Query 1 of 6 in this lesson, at 01-beginner/01-04_time_buckets.md line 15.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

SELECT ts, avg(value) FROM reading
WHERE signal_id = 'AERATION:AHU-1:AIR_FLOW'
  -- Bounded, so the row count is reproducible. Every lesson here bounds its
  -- window; `tools/check_sql.py` runs each query three times and fails any that
  -- return a different number of rows twice, which is how a lesson with a live
  -- plant writing into the database gets caught.
  AND ts < (SELECT max(ts) FROM reading WHERE source = 'seed')
GROUP BY ts;
