-- 01-beginner/01-04_time_buckets.md
-- The query that answers the question
--
-- Query 2 of 6 in this lesson, at 01-beginner/01-04_time_buckets.md line 31.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

SELECT
    date_trunc('hour', r.ts) AS bucket,
    count(*)                 AS n,
    avg(r.value)             AS mean_value,
    min(r.value)             AS min_value,
    max(r.value)             AS max_value
FROM reading r
WHERE r.signal_id = 'AERATION:AHU-1:AIR_FLOW'
  AND r.ts >= (SELECT max(ts) FROM reading) - interval '1 day'
GROUP BY 1
ORDER BY 1 DESC;
