-- 01-beginner/01-04_time_buckets.md
-- `generate_series` makes the missing buckets visible
--
-- Query 6 of 6 in this lesson, at 01-beginner/01-04_time_buckets.md line 203.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

WITH buckets AS (
    SELECT generate_series(
        date_trunc('hour', (SELECT min(ts) FROM reading)),
        date_trunc('hour', (SELECT max(ts) FROM reading)),
        interval '1 hour'
    ) AS bucket
)
SELECT
    b.bucket,
    count(r.signal_id) AS n,          -- 0, not NULL, for an empty hour
    avg(r.value)       AS mean_value
FROM buckets b
LEFT JOIN reading r
       ON r.signal_id = 'AERATION:AHU-1:AIR_FLOW'
      AND date_trunc('hour', r.ts) = b.bucket
GROUP BY b.bucket
ORDER BY b.bucket;
