"""Extract the course's runnable queries into standalone ``.sql`` files.

    python -m tools.extract_sql          # write sql/TablePlus/
    python -m tools.extract_sql --check  # report drift (CI)

## Why these files exist, and why they are generated rather than the source

`sql/NN-stage/NN-NN_lesson.md` is a **lesson**: prose that teaches something,
with a query inside it. That is why the lessons are ``.md`` and always will be —
`02-01_ctes.md` is a thousand words of explanation with five queries in it, and
the explanation is the course. The queries are the easy part.

What was missing is that the queries are not **individually addressable**. From
the markdown you cannot `psql -f` one, link to one, or diff one change. That
matters for a SQL client: the natural thing to want is a folder of files, one per
query, that you can open and run.

So the files are *extracted*, not moved. Same discipline as every other derived
artefact in this project — the Node-RED flows, the Grafana dashboards, the web
page's read model — generated from a source of truth, committed, and checked in CI
by ``--check``.

## Why only 64 of the blocks

The course has 117 fenced ``sql`` blocks and **64 of them run**. The other 53 are
deliberately not runnable:

* ``<!-- check: skip -->`` — a fragment, a syntax sketch, or a query *meant* to
  come back empty (the gaps lesson's "returns nothing, always" is the point);
* or they contain a ``<placeholder>`` for a value the reader supplies.

Extracting those would produce 53 files that fail when opened, which is worse than
not having them. So they stay in the prose, where "this is illustrative" is
obvious from the surrounding sentence and a broken file would not be.

## What each file carries

A header comment with the stage, the lesson, the section heading the query sits
under, and the line number in the markdown — so a failure in TablePlus points back
at ``01-04 line 61`` rather than at a mystery file. That line number is why
``check_sql.py`` records it: "one lesson has a bad query" is not actionable.

The connection string is in the header as a comment, because a SQL client needs
one and putting it in 64 files by hand is how they drift apart.
"""

from __future__ import annotations

import argparse
import logging
import re
import sys
import unicodedata
from pathlib import Path

from tools.check_sql import SQL_BLOCK, _blocks

log = logging.getLogger("tools.extract_sql")

COURSE = Path("sql")
OUT = COURSE / "TablePlus"

#: `## The obvious attempt` / `### Something` — the nearest one above a query is
#: what the query is *for*, and it is the only naming signal a lesson has.
HEADING = re.compile(r"^#{2,4}\s+(?P<title>.+?)\s*$", re.M)

#: A `**Bold lead-in.**` paragraph, used where a lesson has no subheading.
LEAD_IN = re.compile(r"^\*\*(?P<title>[^*]{4,80})\.?\*\*\s*$", re.M)

_SLUG_STRIP = re.compile(r"[^a-z0-9]+")


def slugify(text: str) -> str:
    """`Put the band in the database, not in the query`
    becomes `put-the-band-in-the-database-not-in-the-query`.

    ASCII-folded and lowercased, because a filename that depends on the
    reader's locale is one that differs between two developers' machines — and
    this file is committed and diffed.
    """
    folded = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode()
    return _SLUG_STRIP.sub("-", folded.lower()).strip("-")[:60]


def _context(text: str, offset: int) -> str:
    """The heading or bold lead-in that governs the block starting at `offset`.

    The *nearest* one above, searched in a bounded window so a query fifty lines
    into a long section is not named after a heading from the previous section.
    """
    window = text[:offset]
    # The last 1200 characters is roughly one screen of a lesson.
    window = window[-1200:]

    # **Nearest above, by position.** The first version of this compared titles
    # with `>` and kept the alphabetically greatest, which is not "nearest" by any
    # definition — it named two queries in a row after whichever heading happened
    # to sort last, so `01-02_filtering` produced
    # `01-the-question.sql` *and* `02-the-question.sql` for two different queries.
    # Offsets are the only thing that means "nearest".
    best_pos, best_title = -1, ""
    for pattern in (HEADING, LEAD_IN):
        for match in pattern.finditer(window):
            if match.start() > best_pos:
                best_pos, best_title = match.start(), match.group("title").strip()
    return best_title


def header(lesson: str, section: str, line: int, index: int, total: int) -> str:
    return "\n".join([
        f"-- {lesson}",
        f"-- {section}" if section else "-- (no heading above this query)",
        "--",
        f"-- Query {index} of {total} in this lesson, at {lesson} line {line}.",
        "--",
        "-- GENERATED by `python -m tools.extract_sql` from the lesson above.",
        "-- Edit the lesson, not this file. `make sql-check` runs the lesson's",
        "-- queries against a live database; this copy is for your SQL client.",
        "--",
        "-- Connect with:",
        "--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp",
        "-- (POSTGRES_PORT in .env, and it is often not 5432 — check with",
        "--  `docker compose port db 5432`)",
        "",
        "",
    ])
    # **The blank line is load-bearing.** Without it the query starts on the line
    # straight after the comment block, which is valid SQL — a `--` comment ends
    # at the newline — but it means the header and the query are not separable,
    # and the test that checks "the file's body is the lesson's query byte for
    # byte" had nothing to split on. It reported an empty body for every file.
    # Found by that test, on its first run, for exactly that reason.


def build(course: Path = COURSE) -> dict[Path, str]:
    """Every runnable query, as a relative path -> file content mapping."""
    files: dict[Path, str] = {}

    for lesson in sorted(course.rglob("*.md")):
        if OUT in lesson.parents:
            continue
        rel = lesson.relative_to(course)
        # `01-02_filtering.md` → `01-02_filtering`
        stem = lesson.stem
        if lesson.name == "README.md":
            # An index page, not a lesson — but it holds runnable queries, and the
            # whole point of this directory is that a query is addressable. So it
            # is extracted, under `_index/`, rather than silently dropped.
            #
            # The first version skipped every `README.md` and produced 62 files
            # while `check_sql.py` reported **64** runnable queries. A generator
            # that quietly drops two is worse than one that is short, and the
            # discrepancy is now a test: the two counts must agree.
            stem = "_index"

        blocks = _blocks(lesson)
        if not blocks:
            continue

        text = lesson.read_text(encoding="utf-8")
        # `_blocks` gives the fence line; find the block body at that offset so the
        # section heading can be resolved to the right place rather than guessed.
        offsets = [m.start() for m in SQL_BLOCK.finditer(text)]

        for index, (line, _sql) in enumerate(blocks, start=1):
            # The n-th runnable block is not the n-th fence: skipped blocks are
            # filtered out. Match on the line number instead, which is exact.
            offset = next(
                (o for o in offsets
                 if text[:o].count("\n") + 1 == line),
                None,
            )
            section = _context(text, offset if offset is not None else 0)
            body = next(
                (m.group(1).strip() for m in SQL_BLOCK.finditer(text)
                 if text[: m.start()].count("\n") + 1 == line),
                "",
            )
            name = f"{index:02d}-{slugify(section) or 'query'}.sql"
            path = OUT / rel.parent / stem / name
            head = header(str(rel), section, line, index, len(blocks))
            files[path] = head + body + "\n"

    return files


def check(course: Path = COURSE, out: Path = OUT) -> list[str]:
    problems: list[str] = []
    expected = build(course)

    for path, content in expected.items():
        if not path.exists():
            problems.append(f"{path} does not exist (run: python -m tools.extract_sql)")
        elif path.read_text(encoding="utf-8") != content:
            problems.append(
                f"{path} is out of step with its lesson "
                "(run: python -m tools.extract_sql)"
            )

    # And the reverse: a file with no lesson behind it. Deleting a query from a
    # lesson must delete the file, or the folder accumulates queries that answer
    # questions nobody is asking any more.
    if out.exists():
        for path in sorted(out.rglob("*.sql")):
            if path not in expected:
                problems.append(
                    f"{path} has no query in any lesson "
                    "(run: python -m tools.extract_sql)"
                )
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="tools.extract_sql",
        description="Extract the SQL course's runnable queries into .sql files.",
    )
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--out", type=Path, default=OUT)
    parser.add_argument("--log-level", default="INFO")
    args = parser.parse_args(argv)
    logging.basicConfig(
        level=getattr(logging, args.log_level.upper(), logging.INFO),
        format="%(asctime)s %(levelname)-7s %(name)s %(message)s",
    )

    if args.check:
        problems = check(COURSE, args.out)
        for line in problems:
            log.error("%s", line)
        if problems:
            return 1
        count = len(build(COURSE))
        log.info("all %d extracted queries are in step with the lessons", count)
        return 0

    files = build(COURSE)
    for path, content in sorted(files.items()):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    log.info(
        "wrote %d queries from %d lessons into %s",
        len(files), len({p.parent for p in files}), args.out,
    )
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
