-- 01-beginner/01-02_filtering.md
-- Put the band in the database, not in the query
--
-- Query 3 of 4 in this lesson, at 01-beginner/01-02_filtering.md line 51.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

SELECT
    r.ts,
    r.value,
    s.unit,
    s.normal_low,
    s.normal_high,
    CASE
        WHEN r.value < s.normal_low THEN 'below'
        WHEN r.value > s.normal_high THEN 'above'
        ELSE 'in band'
    END AS position
FROM reading r
JOIN signal s ON s.id = r.signal_id
WHERE r.signal_id = 'EFFLUENT:FLOW:NH4'
  AND r.ts >= (SELECT max(ts) FROM reading) - interval '1 day'
  AND (r.value < s.normal_low OR r.value > s.normal_high)
ORDER BY r.ts;
