-- 01-beginner/01-02_filtering.md
-- The habit that makes filtering safe
--
-- Query 4 of 4 in this lesson, at 01-beginner/01-02_filtering.md line 164.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

SELECT
    count(*)                                          AS everything,
    count(*) FILTER (WHERE r.value IS NOT NULL)      AS with_a_value,
    count(*) FILTER (WHERE r.value < s.normal_low
                       OR r.value > s.normal_high)   AS out_of_band,
    count(*) FILTER (WHERE r.quality = 0)            AS good_quality
FROM reading r
JOIN signal s ON s.id = r.signal_id
WHERE r.signal_id = 'EFFLUENT:FLOW:NH4'
  AND r.ts >= (SELECT max(ts) FROM reading) - interval '3 days';
