-- 01-beginner/01-03_aggregating.md
-- The query that answers the question
--
-- Query 2 of 6 in this lesson, at 01-beginner/01-03_aggregating.md line 36.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

SELECT
    r.signal_id,
    s.unit,
    count(*)                AS readings_total,
    count(r.value)          AS readings_usable,
    count(*) - count(r.value) AS readings_without_a_value,
    avg(r.value)            AS mean_value,
    min(r.value)            AS min_value,
    max(r.value)            AS max_value
FROM reading r
JOIN signal s ON s.id = r.signal_id
WHERE r.signal_id IN ('AERATION:AHU-1:DO', 'EFFLUENT:FLOW:NH4')
  AND r.ts >= (SELECT max(ts) FROM reading) - interval '1 day'
GROUP BY r.signal_id, s.unit
ORDER BY r.signal_id;
