-- 01-beginner/01-03_aggregating.md
-- `HAVING`: filtering the aggregate, not the rows
--
-- Query 3 of 6 in this lesson, at 01-beginner/01-03_aggregating.md line 83.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

SELECT
    r.signal_id,
    s.unit,
    s.normal_low,
    count(*)       AS n,
    avg(r.value)   AS mean_value
FROM reading r
JOIN signal s ON s.id = r.signal_id
WHERE r.ts >= (SELECT max(ts) FROM reading) - interval '1 day'
GROUP BY r.signal_id, s.unit, s.normal_low
HAVING count(*) >= 50 AND avg(r.value) > s.normal_low
ORDER BY mean_value DESC;
