-- 01-beginner/01-03_aggregating.md
-- The question the average cannot answer
--
-- Query 4 of 6 in this lesson, at 01-beginner/01-03_aggregating.md line 148.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

-- Does the sampling rate vary by hour? If it does, the plain mean is suspect.
SELECT
    date_trunc('hour', r.ts) AS bucket,
    count(*)                 AS n,
    avg(r.value)             AS mean_value
FROM reading r
WHERE r.signal_id = 'AERATION:AHU-1:DO'
  AND r.ts >= (SELECT max(ts) FROM reading) - interval '1 day'
GROUP BY 1
ORDER BY 1;
