-- 01-beginner/01-03_aggregating.md
-- Why
--
-- Query 5 of 6 in this lesson, at 01-beginner/01-03_aggregating.md line 213.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

-- and it is the plan, not the data
EXPLAIN SELECT avg(value) FROM reading WHERE signal_id = 'AERATION:AHU-1:AIR_FLOW';
