-- 01-beginner/01-03_aggregating.md
-- When this matters, and when it does not
--
-- Query 6 of 6 in this lesson, at 01-beginner/01-03_aggregating.md line 242.
--
-- GENERATED by `python -m tools.extract_sql` from the lesson above.
-- Edit the lesson, not this file. `make sql-check` runs the lesson's
-- queries against a live database; this copy is for your SQL client.
--
-- Connect with:
--   host=127.0.0.1 port=5432 user=wwtp dbname=wwtp
-- (POSTGRES_PORT in .env, and it is often not 5432 — check with
--  `docker compose port db 5432`)

-- 0.1 m3/h on a 26 000 m3/h range: a real change, and far above the noise floor
SELECT round(avg(value)::numeric, 1) FROM reading
WHERE signal_id = 'AERATION:AHU-1:AIR_FLOW';
